# Generated by Django 2.1.2 on 2018-10-22 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_buddy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='name',
        ),
    ]
