# Generated by Django 2.1.2 on 2018-10-22 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_buddy', '0002_auto_20181022_1204'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
