# Generated by Django 2.1.2 on 2018-10-22 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_buddy', '0005_travel_travelmanager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travel',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='TravelManager',
        ),
        migrations.DeleteModel(
            name='Travel',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
